;;; Old hooks

;(add-hook 'js2-mode-hook '(lambda()
;  (local-set-key (kbd "RET") 'newline-and-indent) ; auto indent
;  (local-set-key (kbd "M-RET") 'newline)
;  (setq c-auto-newline 1)
;  (setq tab-width 4)
;  (setq indent-tabs-mode nil)
;  ;  (setq c-offsets-alist '((brace-list-open . -1)))
;  (setq c-hanging-braces-alist '((brace-list-open . '())
;   (brace-entry-open)
;   (substatement-open after)
;   (block-close . c-snug-do-while)
;   (extern-lang-open after)
;   (inexpr-class-open after)
;   (brace-list-close)
;  (inexpr-class-close before))
; )
;  (setq c-cleanup-list '(brace-catch-brace brace-else-brace brace-elseif-brace))
;
;(setq show-trailing-whitespace t)
;))

;(add-hook 'c-mode-hook '(lambda ()
;  (setq c-basic-offset 2)
;  (setq tab-width 4)
;  (setq indent-tabs-mode nil)
;  (setq c-auto-newline 1)
;;  (setq c-offsets-alist '((brace-list-open . -1)))
;  (setq c-hanging-braces-alist '((brace-list-open . '())
;   (brace-entry-open)
;   (substatement-open after)
;   (block-close . c-snug-do-while)
;   (extern-lang-open after)
;   (inexpr-class-open after)
;   (brace-list-close)
;  (inexpr-class-close before))
;)
;  (setq c-cleanup-list '(brace-catch-brace brace-else-brace brace-elseif-brace))
;
;  (turn-on-auto-fill)
;  (setq comment-column 40)
;;  (setq c-default-style "k&r")
;))

;(defun my-c++-indent-setup ()
;  (setq c-default-style "stroustrup")
;  (setq c-basic-offset 2)
;  (setq tab-width 2)
;  (setq c-auto-newline 1)
;  (setq indent-tabs-mode nil)
;;  (setq indent-tabs-mode 1)
;;  (c-set-style "stroustrup")
;  (setq c-hanging-braces-alist '((brace-list-open . '())
;   (brace-entry-open)
;;   (substatement-open after)
;   (block-close . c-snug-do-while)
;   (extern-lang-open after)
;   (inexpr-class-open after)
;   (brace-list-close)
;   (substatement-open after)
;   (class-open after)
;   (inline-open after)
;   (defun-open after)
;  (inexpr-class-close before))
;)
;)
;(add-hook 'c++-mode-hook 'my-c++-indent-setup)

